title: MissionNET Radio
description: Amateur radio experiments and projects using MOTOTRBO and other digital systems.
theme: jekyll-theme-minimal

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
