title: MissionNET Radio
description: Amateur radio experiments and projects using MOTOTRBO, Harris, and other digital systems.
theme: jekyll-theme-minimal

show_downloads: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
