title: MissionNET Radio
description: Amateur radio experiments and projects using MOTOTRBO, Harris, and other digital systems.
theme: jekyll-theme-minimal

# Build settings
show_downloads: false

# Page defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
